version: '3'

services:
  hadoop-hdfs:
    build: ./hadoop-hdfs
    container_name: hadoop-hdfs
    ports:
      - "50070:50070"
      - "8020:8020"
    volumes:
      - hadoop-namenode:/usr/local/hadoop/hdfs/namenode
      - hadoop-datanode:/usr/local/hadoop/hdfs/datanode

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "8080:8080"
    depends_on:
      - hadoop-hdfs

  hive:
    build: ./hive
    container_name: hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop-hdfs
    environment:
      HADOOP_HOME: /usr/local/hadoop

  presto:
    build: ./presto
    container_name: presto
    ports:
      - "8081:8081"
    depends_on:
      - hadoop-hdfs
      - hive
      - spark
    volumes:
      - ./presto/config.properties:/usr/local/presto/etc/config.properties
      - ./presto/jvm.config:/usr/local/presto/etc/jvm.config
      - ./presto/node.properties:/usr/local/presto/etc/node.properties

volumes:
  hadoop-namenode:
  hadoop-datanode:
