version: '3.8'
services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    build:
      context: .
      dockerfile: Dockerfile.hadoop
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    ports:
      - "9864:9864"

  hive:
    build:
      context: .
      dockerfile: Dockerfile.hive
    container_name: hive
    depends_on:
      - namenode
      - datanode

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker
    depends_on:
      - spark-master

volumes:
  hadoop_namenode:
  hadoop_datanode:
